name: Main
type: base

form:
  fields:

    background:
      type: input.colorpicker
      label: Background Color
      default: "#f7f7f7"

    neutral:
      type: input.colorpicker
      label: Neutral Color
      default: "#dddddd"
    
    accent:
      type: input.colorpicker
      label: Accent Color
      default: "#ffcc33"
      
    offwhite:
      type: input.colorpicker
      label: Off Content
      default: "#ffffff"
    fnote4:
      type: separator.note
      class: sf
      content: <div class='sf-note'><a onclick='javascript:poko_direct_modif(this,"light")' data-ref='[base][background]' data-dst='[base][offwhite]'>Lighter Background</a></div>

    text-color:
      type: input.colorpicker
      label: Text Color
      default: "#222222"

    font:
      type: input.fonts
      label: Body Font
      default: 'clearsans, sans-serif'
    heading-font:
      type: input.fonts
      label: Heading Font
    font-size:
      type: input.text
      label: Font Size
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
      default: 1.5rem
    
    padding:
      type: input.text
      label: Padding
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
      default: 0.5rem

    margin:
      type: input.text
      label: Margin
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
      default: 0.5rem      

      
