name: Main
type: base

form:
  fields:

    snote:
      type: separator.note
      class: nulled
      content: <script>function gasp(d,s) {var sc='input[name=\'styles'+s+'\']';var ds='input[name=\'styles'+d+'\']';document.querySelector(ds).value=document.querySelector(sc).value};document.querySelector(ds).focus();</script>

    font:
      type: input.fonts
      label: Body Font
      default: 'clearsans, sans-serif'
    heading-font:
      type: input.fonts
      label: Heading Font
    font-size:
      type: input.text
      label: Font Size
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
      default: 1.5rem
    
    background:
      type: input.colorpicker
      label: Background
      default: "#f7f7f7"
    text-color:
      type: input.colorpicker
      label: Text Color
      default: "#222222"

    padding:
      type: input.text
      label: Padding
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
      default: 0.5rem
    margin:
      type: input.text
      label: Margin
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
      default: 0.5rem      

    offwhite:
      type: input.colorpicker
      label: Off Content
      default: "#ffffff"
