name: Base
description: Base styles for the theme
type: core

form:
  fields:

    body-font:
      type: input.fonts
      label: Body Font
      default: 'roboto, sans-serif'
    background:
      type: input.colorpicker
      label: Background
      default: "#f7f7f7"
    text-color:
      type: input.colorpicker
      label: Text Color
      default: "#333333"
    heading-font:
      type: input.fonts
      label: Heading Font
    heading-text-color:
      type: input.colorpicker
      label: Heading Color
      default: "#224488"
    fnote:
      type: separator.note
      class: nulled
      content: <div style='padding: 0 10px 0 185px'><a onclick="javascript:gasp('[base][heading-text-color]','[accent][color-3]')">Use Heading Color</a></div>

